/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407_xx_MemMap.h"
#include "gpio.h"
#include "uart.h"
#include "uart_stm32.h"
#include "spi_loopback_feature.h"
#include "circular_buffer.h"
#include "i2c.h"
#include "i2c_gyro_data_handle.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/* SW delay */
void sw_delay()
{
	for(uint32_t i=0; i<900000; i++);
}

int main(void)
{

	extern circular_buffer circ_buffer;

	volatile uint8_t list_menu_sent = 1;
	volatile char current_mode = 0;

	gpio_user_cfg_init();
	spi_init();
    cb_init(&circ_buffer);
    i2c_init();

    USART_RegDef_Struct* pProtUsart = USART2;

	/* Loop forever */
	while(1)
	{
		/* Setting the active user command */
		if (usart_command != 0)
		{
		   current_mode = usart_command;  // Set active mode
		   usart_command = 0;             // Clear the command
		}


		if(list_menu_sent)
		{
			usart_send_string(pProtUsart, "*****Protocol Sniffer Options*****\r\n");
			usart_send_string(pProtUsart, "s = SPI LoopBack Test\r\n");
			usart_send_string(pProtUsart, "i = I2C-Accel Sensor Liner Acceleration Live Data\r\n");
			usart_send_string(pProtUsart, "m = Protocol Sniffer Menu\r\n");

			list_menu_sent = 0;
		}

       /* Handling various user commands */
	   if(current_mode == 's')
	   {
		 usart_send_string(pProtUsart, "[SPI LOOPBACK TEST] ");
		 spi_loopback_test();
		 sw_delay();
	   }
	   else if(current_mode == 'i')
	   {
			  i2c_gyro_sensor_read();
	   }
	   else if(current_mode == 'm')
	   {
		   list_menu_sent = 1;
		   current_mode = 0;
	   }


	}
}
